import {
  AttributeMeta,
  SURVEY_ENTITY_TYPE_ELEMENT,
  QUESTION_TYPE_CHECKBOX,
  QUESTION_TYPE_DROPDOWN,
  QUESTION_TYPE_BUTTON,
  QUESTION_TYPE_IMAGE_SELECT,
  QUESTION_TYPE_MATRIX_COMPOSITE,
  QUESTION_TYPE_MATRIX_TEXT,
  QUESTION_TYPE_MATRIX_NUMBER,
  QUESTION_TYPE_MATRIX_DATE,
  QUESTION_TYPE_MATRIX_TIME,
  QUESTION_TYPE_MATRIX_DATETIME,
  QUESTION_TYPE_MATRIX_CHECKBOX,
  QUESTION_TYPE_MATRIX_YES_NO,
  QUESTION_TYPE_RANKING,
  QUESTION_TYPE_MULTI_PART_TEXT,
  QUESTION_TYPE_MULTI_PART_NUMBER,
  QUESTION_TYPE_MULTI_PART_YES_NO,
  QUESTION_TYPE_MULTI_PART_STAR_RATING,
  QUESTION_TYPE_MULTI_PART_POINT_5,
  QUESTION_TYPE_MULTI_PART_POINT_10,
} from '../types'
import { ATTRIBUTE_CHOICE_RANDOMISE } from '../constants'
import { getNestedValue } from '../helpers'

export const choiceRandomiseMeta: AttributeMeta = {
  id: ATTRIBUTE_CHOICE_RANDOMISE,
  entityTypes: [SURVEY_ENTITY_TYPE_ELEMENT],
  name: 'Randomise',
  description: 'Randomise answer order.',
  typesLimit: [
    QUESTION_TYPE_CHECKBOX,
    QUESTION_TYPE_DROPDOWN,
    QUESTION_TYPE_BUTTON,
    QUESTION_TYPE_IMAGE_SELECT,
    QUESTION_TYPE_MATRIX_COMPOSITE,
    QUESTION_TYPE_MATRIX_TEXT,
    QUESTION_TYPE_MATRIX_NUMBER,
    QUESTION_TYPE_MATRIX_DATE,
    QUESTION_TYPE_MATRIX_TIME,
    QUESTION_TYPE_MATRIX_DATETIME,
    QUESTION_TYPE_MATRIX_CHECKBOX,
    QUESTION_TYPE_MATRIX_YES_NO,
    QUESTION_TYPE_RANKING,
    QUESTION_TYPE_MULTI_PART_TEXT,
    QUESTION_TYPE_MULTI_PART_NUMBER,
    QUESTION_TYPE_MULTI_PART_YES_NO,
    QUESTION_TYPE_MULTI_PART_STAR_RATING,
    QUESTION_TYPE_MULTI_PART_POINT_5,
    QUESTION_TYPE_MULTI_PART_POINT_10,
  ],
  initialValue: false,
  schemaSpec: {
    $type: Boolean,
    $name: 'Randomise',
    $validate: {
      required: true,
    },
  },
  getValue: (entity) => {
    return (
      getNestedValue(entity, `attributes.${ATTRIBUTE_CHOICE_RANDOMISE}`) ||
      false
    )
  },
}
