import {
  ATTRIBUTE_SURVEY_TITLE,
  ATTRIBUTE_SURVEY_PRESENTATION_TITLE,
  ATTRIBUTE_SURVEY_PRESENTATION_WELCOME_MESSAGE,
  ATTRIBUTE_SURVEY_THANK_YOU_LINK_URL,
  ATTRIBUTE_SURVEY_THANK_YOU_LINK_TEXT,
  ATTRIBUTE_SURVEY_THANK_YOU_LINK_SHOW,
  ATTRIBUTE_SURVEY_THANK_YOU_REDIRECT_END,
  ATTRIBUTE_ENTITY_CODE,
  ATTRIBUTE_QUESTION_TYPE,
  ATTRIBUTE_QUESTION_REQUIRED,
  ATTRIBUTE_QUESTION_INPUT_SIZE,
  ATTRIBUTE_QUESTION_LENGTH_MIN_MAX,
  ATTRIBUTE_CHOICE_MIN_MAX,
  ATTRIBUTE_CHOICE_OTHER,
  ATTRIBUTE_CHOICE_RANDOMISE,
  ATTRIBUTE_QUESTION_NUMBER_MIN_MAX,
  ATTRIBUTE_QUESTION_NUMBER_NEG_ALLOWED,
  ATTRIBUTE_CONDITION,
  ATTRIBUTE_MATRIX_ORIENTATION,
  ATTRIBUTE_QUESTION_COLUMNS,
} from 'veysur-common'

import { ATTRIBUTE_CONTENT_TYPE } from '../constant'

import {
  TextInput,
  ThankYouLinkUrlInput,
  YesNo,
  LengthMinMax,
  NumberMinMax,
  SelectionRules,
  DefaultableYesNo,
  ConditionEditor,
  QuestionTypeSelect,
  ContentTypeSelect,
  InputSizeSelect,
  ImageColumnsSelect,
  Dropdown,
} from '../../SurveyAttribute'

/**
 * Maps attribute IDs to their UI components
 * This is the single source of truth for which component renders each attribute
 */
export const attributeComponentMap = {
  [ATTRIBUTE_SURVEY_TITLE]: TextInput,
  [ATTRIBUTE_SURVEY_PRESENTATION_TITLE]: DefaultableYesNo,
  [ATTRIBUTE_SURVEY_PRESENTATION_WELCOME_MESSAGE]: DefaultableYesNo,
  [ATTRIBUTE_SURVEY_THANK_YOU_LINK_URL]: ThankYouLinkUrlInput,
  [ATTRIBUTE_SURVEY_THANK_YOU_LINK_TEXT]: TextInput,
  [ATTRIBUTE_SURVEY_THANK_YOU_LINK_SHOW]: DefaultableYesNo,
  [ATTRIBUTE_SURVEY_THANK_YOU_REDIRECT_END]: DefaultableYesNo,
  [ATTRIBUTE_ENTITY_CODE]: TextInput,
  [ATTRIBUTE_QUESTION_TYPE]: QuestionTypeSelect,
  [ATTRIBUTE_CONTENT_TYPE]: ContentTypeSelect,
  [ATTRIBUTE_QUESTION_REQUIRED]: YesNo,
  [ATTRIBUTE_QUESTION_INPUT_SIZE]: InputSizeSelect,
  [ATTRIBUTE_QUESTION_LENGTH_MIN_MAX]: LengthMinMax,
  [ATTRIBUTE_CHOICE_MIN_MAX]: SelectionRules,
  [ATTRIBUTE_CHOICE_OTHER]: YesNo,
  [ATTRIBUTE_CHOICE_RANDOMISE]: YesNo,
  [ATTRIBUTE_QUESTION_NUMBER_MIN_MAX]: NumberMinMax,
  [ATTRIBUTE_QUESTION_NUMBER_NEG_ALLOWED]: YesNo,
  [ATTRIBUTE_CONDITION]: ConditionEditor,
  [ATTRIBUTE_MATRIX_ORIENTATION]: Dropdown,
  [ATTRIBUTE_QUESTION_COLUMNS]: ImageColumnsSelect,
} as const
