#!/usr/bin/env node
// Regenerates THIRD-PARTY-NOTICES.md from the production dependency trees of the
// published packages. Run via `pnpm license-notices`.
import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const packages = ['api', 'app', 'common']

const copyrightOf = (licenseFile) => {
  if (!licenseFile) return ''
  try {
    const line = readFileSync(licenseFile, 'utf8')
      .split('\n')
      .find((l) => /^\s*(copyright\s*(\(c\)|©|\d)|\(c\))/i.test(l))
    return line ? line.trim() : ''
  } catch {
    return ''
  }
}

const entries = new Map()
for (const name of packages) {
  const out = execFileSync(
    'pnpm',
    ['exec', 'license-checker-rseidelsohn', '--production', '--excludePrivatePackages', '--json'],
    { cwd: join(root, 'package', name), encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 },
  )
  for (const [id, info] of Object.entries(JSON.parse(out))) {
    if (id.startsWith('veysur-')) continue
    entries.set(id, info)
  }
}

const rows = [...entries.entries()]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([id, info]) => {
    const licences = [info.licenses].flat().join(', ')
    const cell = (s) => String(s ?? '').replace(/\|/g, '\\|')
    return `| ${cell(id)} | ${cell(licences)} | ${cell(info.repository)} | ${cell(copyrightOf(info.licenseFile))} |`
  })

const header = `<!-- cspell:disable -->

# Third-party notices

VeySur is licensed under the Elastic License 2.0 (see [LICENSE](LICENSE)). It includes third-party
software under the licences listed below. This file is generated by \`pnpm license-notices\`; do not
edit it by hand.

\`@datacapy/*\` and \`s3-adaptor\` are copyright Kevin Foster and licensed under BSD-3-Clause.

| Package | Licence | Repository | Copyright |
| --- | --- | --- | --- |
`

writeFileSync(join(root, 'THIRD-PARTY-NOTICES.md'), `${header}${rows.join('\n')}\n`)
console.log(`Wrote ${rows.length} entries to THIRD-PARTY-NOTICES.md`)
