export const KEY_STATE_SURVEY_EDITING = 'surveyEditing'
export const KEY_STATE_SURVEY_LIST = 'surveyList'
export const KEY_STATE_SURVEY_FOCUS = 'surveyFocus'
export const KEY_STATE_SURVEY_PARTICIPANT_LIST = 'surveyParticipantList'
export const KEY_STATE_SURVEY_PARTICIPANT_GET = 'surveyParticipantGet'
export const KEY_STATE_SURVEY_PARTICIPANT_ATTRIBUTE_LIST =
  'surveyParticipantAttributeList'
export const KEY_STATE_SURVEY_RESPONSE_LIST = 'surveyResponseList'
export const KEY_STATE_SURVEY_RESPONSE_GET = 'surveyResponseGet'
export const KEY_STATE_SURVEY_RESPONSE_FILES = 'surveyResponseFiles'
export const KEY_STATE_SURVEY_STATS = 'surveyStats'
export const KEY_STATE_SURVEY_SNAPSHOT_LIST = 'surveySnapshotList'
export const KEY_STATE_SURVEY_SNAPSHOT_PUBLISHED = 'surveySnapshotPublished'
export const KEY_STATE_SURVEY_SNAPSHOT = 'surveySnapshot'
export const KEY_STATE_SURVEY = 'survey'
export const KEY_STATE_SURVEY_EMAIL_TEMPLATES = 'surveyEmailTemplates'
export { KEY_STATE_AUTH, KEY_STATE_PROJECT_DOMAIN } from 'common/keyState'
export const KEY_STATE_PUBLICATION_ACTIVE = 'publicationActive'
export const KEY_STATE_PUBLICATION_HAS_CHANGES = 'publicationHasChanges'
export const KEY_STATE_PUBLICATION_LIST = 'publicationList'
export const KEY_STATE_FEATURE_GATES = 'featureGates'
